# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('Datos', 'Datos'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Red', 'Red'), ('Servicio', 'Servicio'), ('Instalación', 'Instalación'), ('Personas', 'Personas')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('confidencialidad', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto'), (4, '4 - Crítico')], verbose_name='Confidencialidad (C)')),
                ('integridad', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto'), (4, '4 - Crítico')], verbose_name='Integridad (I)')),
                ('disponibilidad', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto'), (4, '4 - Crítico')], verbose_name='Disponibilidad (D)')),
                ('datos_sensibles', models.BooleanField(default=False, verbose_name='Datos sensibles (LOPDP)')),
                ('nivel_criticidad', models.IntegerField(default=1, editable=False, verbose_name='Nivel de criticidad')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-nivel_criticidad', 'nombre'],
            },
        ),
    ]
