# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_propietario', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
    ]
