# Generated by Django 4.2.13 on 2026-07-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='departamento',
            field=models.CharField(choices=[('Tecnología', 'Tecnología'), ('Finanzas', 'Finanzas'), ('Recursos Humanos', 'Recursos Humanos'), ('Administración', 'Administración'), ('Operaciones', 'Operaciones'), ('Legal y Cumplimiento', 'Legal y Cumplimiento'), ('Ventas y Marketing', 'Ventas y Marketing')], max_length=100, verbose_name='Departamento'),
        ),
    ]
