# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_residual', models.IntegerField(choices=[(1, '1 - Rara vez'), (2, '2 - Poco probable'), (3, '3 - Probable'), (4, '4 - Casi seguro')], verbose_name='Probabilidad residual')),
                ('impacto_residual', models.IntegerField(choices=[(1, '1 - Insignificante'), (2, '2 - Menor'), (3, '3 - Moderado'), (4, '4 - Catastrófico')], verbose_name='Impacto residual')),
                ('riesgo_residual', models.IntegerField(default=0, editable=False, verbose_name='Riesgo residual')),
                ('nivel_cualitativo', models.CharField(editable=False, max_length=10, verbose_name='Nivel cualitativo')),
                ('aceptacion', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=10, verbose_name='Decisión')),
                ('resp_aprobacion', models.CharField(blank=True, max_length=200, verbose_name='Responsable de aprobación')),
                ('fecha_decision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de decisión')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Riesgo residual',
                'verbose_name_plural': 'Riesgos residuales',
                'ordering': ['-riesgo_residual'],
            },
        ),
    ]
