# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riesgos', '0001_initial'),
        ('tratamiento', '0001_initial'),
        ('residual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgoresidual',
            name='id_riesgo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residual', to='riesgos.riesgo', verbose_name='Riesgo'),
        ),
        migrations.AddField(
            model_name='riesgoresidual',
            name='id_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamiento.tratamiento', verbose_name='Tratamiento'),
        ),
    ]
