# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riesgos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(choices=[('Mitigar', 'Mitigar'), ('Transferir', 'Transferir'), ('Evitar', 'Evitar'), ('Aceptar', 'Aceptar')], max_length=15, verbose_name='Estrategia')),
                ('nombre_control', models.CharField(max_length=200, verbose_name='Nombre del control')),
                ('descripcion_ctrl', models.TextField(verbose_name='Descripción del control')),
                ('tipo_control', models.CharField(choices=[('Técnico', 'Técnico'), ('Administrativo', 'Administrativo'), ('Físico', 'Físico')], max_length=20, verbose_name='Tipo de control')),
                ('funcion_control', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Detectivo', 'Detectivo'), ('Correctivo', 'Correctivo')], max_length=15, verbose_name='Función del control')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('fecha_objetivo', models.DateField(verbose_name='Fecha objetivo')),
                ('estado_control', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Implementado', 'Implementado')], default='Pendiente', max_length=15, verbose_name='Estado del control')),
                ('justificacion', models.TextField(blank=True, help_text='Obligatoria si estrategia = Aceptar', verbose_name='Justificación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('id_riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento', to='riesgos.riesgo', verbose_name='Riesgo')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['fecha_objetivo'],
            },
        ),
    ]
