# Generated by Django 4.2.13 on 2026-07-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlISO27001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del control')),
                ('categoria', models.CharField(choices=[('Organizacional', 'Organizacional'), ('Personas', 'Personas'), ('Físico', 'Físico'), ('Tecnológico', 'Tecnológico')], max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Control ISO 27001',
                'verbose_name_plural': 'Controles ISO 27001',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Cuándo se completó la implementación', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_inicio_ejecucion',
            field=models.DateField(blank=True, help_text='Cuándo se inició la implementación del control', null=True, verbose_name='Fecha de inicio de ejecución'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_planificacion',
            field=models.DateField(blank=True, help_text='Cuándo se planificó este tratamiento', null=True, verbose_name='Fecha de planificación'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='control_iso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='tratamiento.controliso27001', verbose_name='Control ISO 27001 de referencia'),
        ),
    ]
