# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('amenazas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.IntegerField(choices=[(1, '1 - Rara vez'), (2, '2 - Poco probable'), (3, '3 - Probable'), (4, '4 - Casi seguro')], verbose_name='Probabilidad')),
                ('impacto', models.IntegerField(choices=[(1, '1 - Insignificante'), (2, '2 - Menor'), (3, '3 - Moderado'), (4, '4 - Catastrófico')], verbose_name='Impacto')),
                ('riesgo_inherente', models.IntegerField(default=0, editable=False, verbose_name='Riesgo inherente')),
                ('nivel_cualitativo', models.CharField(editable=False, max_length=10, verbose_name='Nivel cualitativo')),
                ('estado_riesgo', models.CharField(choices=[('Evaluado', 'Evaluado'), ('En tratamiento', 'En tratamiento'), ('Con residual', 'Con residual'), ('Cerrado', 'Cerrado')], default='Evaluado', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('id_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo')),
                ('id_amenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.amenaza', verbose_name='Amenaza')),
            ],
            options={
                'verbose_name': 'Evaluación de riesgo',
                'verbose_name_plural': 'Evaluaciones de riesgo',
                'ordering': ['-riesgo_inherente', '-fecha_evaluacion'],
            },
        ),
    ]
