# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vulnerabilidades', '0001_initial'),
        ('riesgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgo',
            name='id_usuario_registra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='id_vulnerabilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilidades.vulnerabilidad', verbose_name='Vulnerabilidad'),
        ),
    ]
