# Generated by Django 4.2.13 on 2026-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgo',
            name='controles_existentes',
            field=models.TextField(blank=True, help_text='Controles de seguridad ya implementados antes de esta evaluación', verbose_name='Controles existentes'),
        ),
    ]
