# Generated by Django 4.2.13 on 2026-07-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0003_riesgo_controles_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgo',
            name='nombre',
            field=models.CharField(blank=True, help_text='Descripción literal de qué es el riesgo. Si se deja vacío, se genera automáticamente.', max_length=250, verbose_name='Título del riesgo'),
        ),
    ]
