# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cvss_score', models.FloatField(blank=True, help_text='0.0 – 10.0', null=True, verbose_name='CVSS Score')),
                ('severidad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], max_length=10, verbose_name='Severidad')),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidencia')),
                ('estado', models.CharField(choices=[('Identificada', 'Identificada'), ('En tratamiento', 'En tratamiento'), ('Resuelta', 'Resuelta')], default='Identificada', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilidades', to='activos.activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
