# Generated by Django 4.2.13 on 2026-07-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Cadena de vector CVSS v3.1 generada por la calculadora', max_length=60, verbose_name='Vector CVSS'),
        ),
    ]
