# Generated by Django 4.2.13 on 2026-07-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0001_initial'),
        ('vulnerabilidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilidad',
            name='amenaza_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amenazas.amenaza', verbose_name='Amenaza asociada'),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cve_id',
            field=models.CharField(blank=True, help_text='Ej: CVE-2024-1234', max_length=50, verbose_name='CVE ID'),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='Cadena de vector CVSS v3.1 generada por la calculadora', max_length=60, verbose_name='Vector CVSS'),
        ),
    ]
