# Generated by Django 6.0.6 on 2026-07-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0001_initial'),
        ('vulnerabilidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilidad',
            name='amenaza_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amenazas.amenaza', verbose_name='Amenaza asociada'),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cve_id',
            field=models.CharField(blank=True, help_text='Ej: CVE-2024-1234', max_length=50, verbose_name='CVE ID'),
        ),
    ]
