# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoAmenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Activo-Amenaza',
            },
        ),
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_amenaza', models.CharField(choices=[('Natural', 'Natural'), ('Humana deliberada', 'Humana deliberada'), ('Humana accidental', 'Humana accidental'), ('Tecnológica', 'Tecnológica')], max_length=30, verbose_name='Tipo')),
                ('fuente_amenaza', models.CharField(choices=[('Externa', 'Externa'), ('Interna', 'Interna'), ('Mixta', 'Mixta')], max_length=10, verbose_name='Fuente')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activos', models.ManyToManyField(blank=True, through='amenazas.ActivoAmenaza', to='activos.activo', verbose_name='Activos asociados')),
            ],
            options={
                'verbose_name': 'Amenaza',
                'verbose_name_plural': 'Amenazas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='activoamenaza',
            name='id_amenaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.amenaza', verbose_name='Amenaza'),
        ),
        migrations.AlterUniqueTogether(
            name='activoamenaza',
            unique_together={('id_activo', 'id_amenaza')},
        ),
    ]
