# Generated by Django 4.2.13 on 2026-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('desactivar', 'Desactivar'), ('login', 'Login'), ('eliminar', 'Eliminar')], max_length=20, verbose_name='Acción')),
                ('entidad_afectada', models.CharField(max_length=100, verbose_name='Entidad')),
                ('id_entidad', models.IntegerField(blank=True, null=True, verbose_name='ID Entidad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Log de auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
